### ISSUE TITLE
Error in System view JSON for springframework

### ISSUE THREAD

**Issue by pomba123** [LabES-2021Q3-Annotation-Sniffer/asniffer#12]
The system view JSON contains error for the springframework project,

                {
                  "name": "org.springframework.boot.context.properties.bind",
                  "type": "schema",
                  "value": 6,
                  "properties": {},
                  "children": [
                    {
                      "name": "org.springframework.boot.context.properties.bind.handler",
                      "type": "package",
                      "properties": {},
                      "children": [
                        {
                          "name": "java.lang",
                          "type": "schema",
                          "value": 6,
                          "properties": {},
                          "children": []
                        },
                        {
                          "name": "org.junit.jupiter.api",
                          "type": "schema",
                          "value": 17,
                          "properties": {},
                          "children": []
                        }
                      ]
                    },
                    {
                      "name": "org.springframework.boot.context.properties.bind.test",
                      "type": "package",
                      "properties": {},
                      "children": [
                        {
                          "name": "org.junit.jupiter.api",
                          "type": "schema",
                          "value": 2,
                          "properties": {},
                          "children": []
                        }
                      ]
                    },
                    {
                      "name": "org.springframework.boot.context.properties.bind.validation",
                      "type": "package",
                      "properties": {},
                      "children": [
                        {
                          "name": "java.lang",
                          "type": "schema",
                          "value": 13,
                          "properties": {},
                          "children": []
                        },
                        {
                          "name": "org.junit.jupiter.api",
                          "type": "schema",
                          "value": 31,
                          "properties": {},
                          "children": []
                        },
                        {
                          "name": "org.springframework.validation.annotation",
                          "type": "schema",
                          "value": 4,
                          "properties": {},
                          "children": []
                        },
                        {
                          "name": "javax.validation.constraints",
                          "type": "schema",
                          "value": 6,
                          "properties": {},
                          "children": []
                        },
                        {
                          "name": "javax.validation",
                          "type": "schema",
                          "value": 2,
                          "properties": {},
                          "children": []
                        }
                      ]
                    }
                  ]

the previous code shows a schema having packages and other schemas as children. 

The occurence of this bug is located in the package org.springframework.boot.context.properties.bind, which is being represented as annotation schema, instead of a package.

The JSON was generated by ASniffer javaparser version. 
The springframework release was https://github.com/spring-projects/spring-boot/releases/tag/v2.6.0-M3 .

**Comment by phillima** [comment]
This bug is related to the issue #22
