### ISSUE TITLE
ClassModel.getElementReport() is indetermined

### ISSUE THREAD

**Issue by felipemandu** [LabES-2021Q3-Annotation-Sniffer/asniffer#16]
The method can give two or more different responses in the same context.

**Comment by brusangues** [comment]
Children.getChildByName() has the same behaviour. May be related to #12.

**Comment by brusangues** [comment]
If the behaviour stays the same, the method's names could be renamed to include the word "first" in their names.
Such as: ClassModel.getFirstElementReport().

This way, the method's names would better represent their behaviours.
