### ISSUE TITLE
Define an approach to deal with annotations that were imported with wild card

### ISSUE THREAD

**Issue by phillima** [LabES-2021Q3-Annotation-Sniffer/asniffer#22]
Code Annotations can be imported with the wild card. Consider the image below:

![image](https://user-images.githubusercontent.com/6624233/140192050-a2a28497-5c08-4dd0-bd00-5481cc171dcb.png)

Annotations @GetMapping, @RestController, @ResponseBody and, @RequestParam are all being imported from schema ```org.springframework.web.bind.annotation.*```. However, then parser has no obvious way of obtaing this information, since everything becomes a text.

If no precise schema is able to be extracted, the ASniffer should inform what potential schema was used to import the annotation.

The following order should be used to determine what is the schema:
- Check if it is inline imported. 
- Check if it belongs to the ```java.lang``` schema
- Check if a match can be found between the import and the annotation simple name (identifier)
- If no previous match was obtained, check if there is an import with the wild card (isAsterisk()). If not, the annotation was declared in the same package being used. Hence the schema is the package.
- If there is an import with the wild card, inform all of them in the schema properties for the annotation. Therefore, the schema will become a list of potential schemas.

**Comment by brusangues** [comment]
The above order and conditionals will be implemented as specified, with the following exceptions:
 * From now on, the schemas will always be returned as lists;
 * In regards to the fith bullet point above, the packages will also be added to the list of potential schemas.
 
 The implementation will be referenced in the issue #27

**Comment by phillima** [comment]
### Updates
In this minor release, a glossary should be implemented to try to resolve annotations imported with wildcard.

For this first release this will be following frameworks inserted in the glossary:

- Spring
- JPA
- JUnit

The ASniffer should determine the schema in the following order:
1. Check if the annotation was imported inline
2. Check if there is a match between the annotation name and the imported package
3. Check the glossary. 
3.1. For instance, if looking for the annotation **RestController**, the glossary will report that the schema should be **org.springframework.web.bind.annotation**. 
3.2 If the class being analyzed contains this import as a wildcard, **org.springframework.web.bind.annotation.***, then likely this is the schema
4. Check if the annotation belongs to the **java.lang**
5. The last option is that the annotation defined in the same package, in other words, the package of the class is the schema.

To unit test this scenario, the method test **testSchemaWithWildCardImport**, line 222 in the file **TestAnnotationSchema** should pass. It is currently being ignored.
The file used as target test is the **TestSchemaWildCard**.

**Comment by MaikHenriqueSP** [comment]
Closing as approach was defined and the implementation was done accordingly on issue #27.
